// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs0_k0oKrphuVpkWxo3ScqMuDNfZMfbpA',
    appId: '1:809393904120:web:a30a6ce0c479c9fda11e0d',
    messagingSenderId: '809393904120',
    projectId: 'twitter-app-9b8a5',
    authDomain: 'twitter-app-9b8a5.firebaseapp.com',
    storageBucket: 'twitter-app-9b8a5.appspot.com',
    measurementId: 'G-FN0N5DXRC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzK7887D_E2NDiuo9hE8Uukj3ubRGAJhM',
    appId: '1:809393904120:android:b60e6baf0f5b675aa11e0d',
    messagingSenderId: '809393904120',
    projectId: 'twitter-app-9b8a5',
    storageBucket: 'twitter-app-9b8a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKl7V6FIHsc9iO6-G0c4m3bBCjle6unWA',
    appId: '1:809393904120:ios:f14434a251e395a7a11e0d',
    messagingSenderId: '809393904120',
    projectId: 'twitter-app-9b8a5',
    storageBucket: 'twitter-app-9b8a5.appspot.com',
    iosClientId:
        '809393904120-mh3ro8ihbuabrom6cgoa1v4ee7g0agft.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterApp',
  );
}
